fail_fast: true
exclude: |
  (?x)(
    \.snap$
    | src/generated
  )
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/lasuillard-s/devobs
    rev: v0.2.7
    hooks:
      - id: assert-diff
        args: [--target, ./src/generated, --, npm, run, generate]

  - repo: local
    hooks:
      - id: biome-check
        name: biome check (fix)
        language: system
        types_or: [javascript, ts]
        entry: npm exec -- biome check
        args: [--write, --no-errors-on-unmatched]

      - id: biome-format
        name: biome format
        language: system
        types_or: [javascript, ts, json]
        entry: npm exec -- biome format
        args: [--write, --no-errors-on-unmatched]

      - id: typescript
        name: typescript
        language: system
        types_or: [javascript, ts]
        pass_filenames: false
        entry: npm exec -- tsc
        args: [--noEmit]

      - id: vitest
        name: vitest
        language: system
        types_or: [javascript, ts]
        pass_filenames: false
        entry: npm run test
