version: '3'

services:
  workspace:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: workspace
    ports:
      - ${VITEST_UI_HOST:-127.0.0.1}:${VITEST_UI_PORT:-51204}:51204 # Vitest UI
    environment:
      CONTAINER: 1
    command: sleep infinity
    init: true
    extra_hosts:
      - host.docker.internal:host-gateway
