name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  autogenerate:
    name: Autogenerate
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    outputs:
      # If the generated code has changed, this will be set to "true" and new changes will be pushed to the PR
      # causing a new CI run; that's why other jobs should be skipped when this is set to "true".
      changed: ${{ steps.generate.outputs.changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.head_ref || github.ref }}

      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: package.json
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Verify generated code is up-to-date
        id: generate
        run: |
          if pipx run 'devobs~=0.2.6' assert-diff --target ./src/generated -- npm run generate; then
            echo "changed=false" | tee --append "$GITHUB_OUTPUT"
          else
            echo "changed=true" | tee --append "$GITHUB_OUTPUT"
          fi

      - name: Re-raise failure if not dependency update
        if: steps.generate.outputs.changed == 'true' && !startsWith(github.head_ref, 'renovate/org.openapitools-openapi-generator-')
        run: exit 1

      - name: Generate GitHub App token
        if: github.event_name == 'pull_request' && steps.generate.outputs.changed == 'true' && startsWith(github.head_ref, 'renovate/org.openapitools-openapi-generator-')
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: generate-token
        with:
          client-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Push generated client code if dependency update
        if: github.event_name == 'pull_request' && steps.generate.outputs.changed == 'true' && startsWith(github.head_ref, 'renovate/org.openapitools-openapi-generator-')
        uses: iarekylew00t/verified-bot-commit@42a042b0407248f3c0acac00c389e729e3476e86 # v2.3.5
        with:
          token: ${{ steps.generate-token.outputs.token }}
          ref: ${{ github.head_ref }}
          files: |
            src/generated/**
          message: Autogenerate OpenAPI client

  lint:
    name: Lint
    needs: autogenerate
    if: needs.autogenerate.outputs.changed == 'false'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: package.json
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Check formatting with Biome
        run: npm run fmt:check

      - name: Lint with Biome
        run: npm run lint

      - name: Type check with TypeScript
        run: npm run typecheck

  test:
    name: Test
    needs: autogenerate
    if: needs.autogenerate.outputs.changed == 'false'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: package.json
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Run tests
        env:
          __RAINDROP_CLIENT_TEST_API_TOKEN: ${{ secrets.__RAINDROP_CLIENT_TEST_API_TOKEN }}
        run: npm run test:unit

      - name: Run type tests
        run: npm run test:type

      - name: Try build
        run: npm run build

      - name: Upload test results to codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          use_oidc: true
          fail_ci_if_error: false
          report_type: test_results
          files: junit.xml,typecheck.junit.xml

      - name: Upload coverage report
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          use_oidc: true
          fail_ci_if_error: false
          files: coverage/clover.xml
