name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: read-all

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: yarn

      - name: Install deps
        run: yarn install --frozen-lockfile

      - uses: pre-commit/action@v3.0.1
        env:
          RAINDROP_API_TOKEN: ${{ secrets.RAINDROP_API_TOKEN }}

      # NOTE: Disabled for reason: manual intervention & update on codes are required
      # - uses: pre-commit-ci/lite-action@v1.1.0
      #   if: always()

      - name: Try build
        run: yarn run build

      - name: Upload test results to codecov
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true
          fail_ci_if_error: false
          report_type: test_results
          files: junit.xml,typecheck.junit.xml

      - name: Upload coverage report
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true
          fail_ci_if_error: false
          files: coverage/clover.xml
