name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: package.json
          cache: npm

      - name: Update npm
        run: npm install --global npm@latest

      - name: Install deps
        run: npm ci

      - name: Verify generated code is up-to-date
        run: make generate

      - name: Check formatting with Biome
        run: npm run fmt:check

      - name: Lint with Biome
        run: npm run lint

      - name: Type check with TypeScript
        run: npm run typecheck

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: package.json
          cache: npm

      - name: Update npm
        run: npm install --global npm@latest

      - name: Install deps
        run: npm ci

      - name: Run tests
        env:
          RAINDROP_API_TOKEN: ${{ secrets.RAINDROP_API_TOKEN }}
        run: npm run test:unit

      - name: Run type tests
        run: npm run test:type

      - name: Try build
        run: npm run build

      - name: Upload test results to codecov
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true
          fail_ci_if_error: false
          report_type: test_results
          files: junit.xml,typecheck.junit.xml

      - name: Upload coverage report
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true
          fail_ci_if_error: false
          files: coverage/clover.xml
