name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: npm

      - name: Install deps
        run: npm ci

      - uses: pre-commit/action@v3.0.1
        env:
          SKIP: vitest

      # NOTE: Disabled for reason: manual intervention & update on codes are required
      # - uses: pre-commit-ci/lite-action@v1.1.0
      #   if: always()

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Run tests
        env:
          RAINDROP_API_TOKEN: ${{ secrets.RAINDROP_API_TOKEN }}
        run: npm run test:unit

      - name: Run type tests
        run: npm run test:type

      - name: Try build
        run: npm run build

      - name: Upload test results to codecov
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true
          fail_ci_if_error: false
          report_type: test_results
          files: junit.xml,typecheck.junit.xml

      - name: Upload coverage report
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true
          fail_ci_if_error: false
          files: coverage/clover.xml
