name: Docs

on:
  push:
    tags: [v*]

jobs:
  build-docs:
    name: Build Docs
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version-file: package.json
          cache: npm

      - name: Update npm
        run: npm install --global npm@latest

      - name: Install deps
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Generate API docs
        run: npm run make-docs

      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: docs/

  deploy-docs:
    name: Deploy Docs
    needs: build-docs
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    concurrency:
      group: pages
      cancel-in-progress: false
    steps:
      - name: Publish API docs to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
