name: Release

on:
  push:
    tags: [v*]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    environment: npm
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version-file: package.json
          cache: npm
          registry-url: https://registry.npmjs.org
          scope: "@lasuillard"

      # https://docs.npmjs.com/trusted-publishers#github-actions-configuration
      - name: Update npm
        run: npm install --global npm@latest

      - name: Install deps
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Archive build
        run: tar -czvf dist.tar.gz dist

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: dist.tar.gz

      - name: Publish package
        run: npm publish
