name: Release

on:
  push:
    tags: [v*]

permissions: read-all

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    environment: npm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: yarn
          registry-url: https://registry.npmjs.org
          scope: "@lasuillard"

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Build app
        run: yarn run build

      - name: Archive build
        run: tar -czvf dist.tar.gz dist

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: dist.tar.gz

      - name: Publish package
        run: yarn publish
