name: Release

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish-npm:
    name: Publish to npm
    runs-on: ubuntu-latest
    environment: npm
    timeout-minutes: 10
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: package.json
          cache: npm
          registry-url: https://registry.npmjs.org
          scope: "@lasuillard"

      - name: Install deps
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Archive build
        run: tar --create --gzip --verbose --file=dist.tar.gz dist

      - name: Create release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          generate_release_notes: false
          files: dist.tar.gz

      - name: Publish package
        run: npm publish
